language: swift
osx_image: xcode11.1
xcode_project: AnyImagePicker.xcworkspace
xcode_scheme: Example

cache: cocoapods
podfile: Podfile

env:
  - DESTINATION='platform=macOS' SWIFT_VERSION=5.1
  - DESTINATION='platform=iOS Simulator,name=iPhone 8' SWIFT_VERSION=5.1

before_install:
  - gem install xcpretty --no-document --quiet
  - gem install cocoapods --pre --no-document --quiet
  - pod install 

script:
  - pod repo update

after_success:
  - sleep 3