name: AnyImageKit CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  iOS:
    name: Test iOS
    runs-on: macOS-latest
    
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
      
    strategy:
      swift-version: [5.3]

    steps:
    - uses: actions/checkout@v2
    - name: Archive for Device slice
      run: xcodebuild archive -project AnyImageKit.xcodeproj -scheme AnyImageKit -configuration Release -destination "generic/platform=iOS"  -archivePath "Build/AnyImageKit.framework-iphoneos.xcarchive" SKIP_INSTALL=NO
    
  iOS Simulator:
    name: Test iOS Simulator
    runs-on: macOS-latest

    env:
      DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
    
    strategy:
      matrix:
        swift-version: [5.3]

    steps:
    - uses: actions/checkout@v2
    - name: Archive for Simulator slice
      run: xcodebuild archive -project AnyImageKit.xcodeproj -scheme AnyImageKit -configuration Release -destination "generic/platform=iOS Simulator" -archivePath "Build/AnyImageKit.framework-iphonesimulator.xcarchive" SKIP_INSTALL=NO
    
  Mac Catalyst:
    name: Test Mac Catalys
    runs-on: macOS-latest

    env:
      DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
      
    strategy:
      swift-version: [5.3]
    
    steps:
    - uses: actions/checkout@v2
    - name: Archive for Mac Catalyst slice
      run: xcodebuild archive -project AnyImageKit.xcodeproj -scheme AnyImageKit -configuration Release -destination "platform=macOS,arch=x86_64,variant=Mac Catalyst" -archivePath "Build/AnyImageKit.framework-catalyst.xcarchive" SKIP_INSTALL=NO
