name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  iOS:
    name: Test iOS
    runs-on: macOS-latest
    
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
      
    strategy:
      matrix:
        destination: ['iOS Simulator,name=iPhone 11']
        swift-version: [5.3]

    steps:
    - uses: actions/checkout@v2
    - name: Install CocoaPods
      run: sudo gem install cocoapods
    - name: Pod Install
      run: pod install 
    - name: Build
      run: xcodebuild -workspace AnyImageKit.xcworkspace -scheme Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
